version: '3'

services:
  ce-users-application:
    image: ce-users-application
    build:
      context: ./
      dockerfile: users-application/Dockerfile
    volumes:
      - /data/ce-testobject
    ports:
      - "8082:8082"
    networks:
      - ce-testobject-network

  ce-working-conditions-application:
    image: ce-working-conditions-application
    build:
      context: ./
      dockerfile: working-conditions-application/Dockerfile
    volumes:
      - /data/ce-testobject
    ports:
      - "8083:8083"
    networks:
      - ce-testobject-network

networks:
  ce-testobject-network: