FROM openjdk:11
ADD /working-conditions-application/target/ce-testobject-working-conditions-application-*-exec.jar ce-testobject-working-conditions.jar
EXPOSE 8083
ENTRYPOINT ["java","-jar","ce-testobject-working-conditions.jar"]